[package]
name = "btmeister"
version = "0.3.9"
edition = "2021"
authors = [ "Haruaki TAMADA" ]
license-file = "LICENSE"
description = "A tool for detecting build tools in use of the projects"
repository = "https://github.com/tamada/btmeister"
homepage = "https://tamada.github.io/btmeister/"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["build", "tools", "detection"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    clap = { version = "3.1.9", features = ["derive"] }
    serde = { version = "1.0.136", features = ["derive"] }
    serde_json = "1.0"
    thiserror = "1.0.30"
    ignore = "0.4.18"
    rust-embed="6.4.0"

[build_dependencies]
    clap = { version = "3.1.9", features = ["derive"] }
    clap_complete = "3.1.4"
    thiserror = "1.0.30"

[package.metadata.scripts]
    hello = "echo \"Hello World\""
    coverage = "cargo llvm-cov --html; mkdir -p site/static/coverage; cp -r target/llvm-cov/html/* site/static/coverage/"
    server = "hugo -s site server"
    site = "hugo -s site"
