[package]
name = "btmeister"
version = "0.1.0"
edition = "2021"
authors = [ "Haruaki TAMADA" ]
license-file = "LICENSE"
description = "A tool for detecting build tools of the projects"
repository = "https://github.com/tamada/btmeister"
homepage = "https://tamada.github.io/btmeister/"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["build", "tools", "detection"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    clap = { version = "3.1.9", features = ["derive"] }
    thiserror = "1.0.30"
    serde = { version = "1.0.136", features = ["derive"] }
    serde_json = "1.0"
    ignore = "0.4.18"
    rust-embed="6.4.0"

[package.metadata.scripts]
    hello = "echo \"Hello World\""
    site = "hugo -s site"