name: docker_image

on:
  workflow_run:
    workflows:
      - "publish_site_release_assets"
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - name: Get latest tag name
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Git Tag name
        id: vars
        run: |
          HEAD_REF=${{ github.head_ref }}
          echo "::set-output name=tag::${HEAD_REF##*/v}"

# docker image
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/btmeister:${{ steps.latest-tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/btmeister:latest

