name: docker_image

on:
  workflow_run:
    workflows:
      - "publish_site_release_assets"
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # タグ名を 1.2.3 のように付けていることが前提．
      - name: Git Tag name
        id: vars
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "env.TAG: ${{ env.TAG }}"
          gh release view --json tagName --jq .tagName
          git tag --sort version:refname
          tag=$(gh release view --json tagName --jq .tagName)
          echo "::set-output name=tag::${tag##v}"

# docker image
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/btmeister:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/btmeister:latest

